#spring:
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedHeaders: "Content-Type"
#            allowedMethods:
#            - GET
#            - POST
#            - PUT
#            - DELETE

#spring:
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin